name: Python

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Set up Python venv and Poetry
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install Dependencies
        run: |
          source .venv/bin/activate
          poetry install

      - name: Check Format
        run: |
          source .venv/bin/activate
          make check-format

      - name: Lint
        run: |
          source .venv/bin/activate
          make lint
